language: java
jdk:
- oraclejdk8
rvm:
- 2.3.1
install:
- rvm install ruby-2.3.1
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr package doc
after_success:
- bash <(curl -s https://codecov.io/bash)
git:
  depth: false
